//shopping cart
export const ADD_TO_THE_CART = "ADD_TO_THE_CART";
export const REMOVE_FROM_THE_CART = "REMOVE_FROM_THE_CART";

//api request
export const FETCH_FURNITURE_REQUEST = "FETCH_FURNITURE_REQUEST";
export const FETCH_FURNITURE_SUCCESS = "FETCH_FURNITURE_SUCCESS";
export const FETCH_FURNITURE_ERORR = "FETCH_FURNITURE_ERROR";
